Fix creation of SentientHome dir and check for success

diff --git a/install b/install
--- a/install
+++ b/install
@@ -101,7 +101,14 @@ else
 fi
 
 # Clone SentientHome deployment repo
-mkdir -f $SENTIENTHOME_PREFIX/SentientHome
+
+log "Creating backup dir: $BACKUPDIR ..."
+mkdir -p $SENTIENTHOME_PREFIX/SentientHome 1>$OPT_OUTPUT
+if [ $? -ne 0 ]; then
+  log "👎  Fatal error creating SentientHome dir: $SENTIENTHOME_PREFIX/SentientHome"
+  exit 2
+fi
+
 $( cd "$SENTIENTHOME_PREFIX"/SentientHome && git clone "$SENTIENTHOME_REPO" )
 
 # Run Setup
