Perform potential firmware upgrade

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -6,6 +6,7 @@
 usage()
 {
   cat << EOF
+
 usage: $0 [options]
 
 Initial setup of the SentientHome Master
@@ -86,6 +87,7 @@ header
 # Default settings
 DEBUG=0
 FORCE=0
+REBOOT=0
 
 # translate long options to short
 for arg
@@ -124,7 +126,18 @@ else
   OPT_OUTPUT="/dev/null"
 fi
 
-# TODO: Mount HDD/SDD
+# Update RPI
+log "Checking for Raspberry firmware update ..."
+( JUST_CHECK=1 && rpi-update 1>$OPT_OUTPUT )
+
+if [ $EXITCODE -eq 2 ]; then
+  log "Updating Raspberry firmware. This can take a while ..."
+  rpi-update 1>$OPT_OUTPUT
+  REBOOT=1
+elif [ $EXITCODE -ne 0 ]; then
+  log "👎  Error checking Raspberry firmware."
+  exit 2
+fi
 
 # Update all packages
 log "Updating all packages. This can take a while ..."
@@ -140,9 +153,6 @@ aptget install python3-dev
 aptget install python3-pip
 aptget install expect
 aptget install pass
-
-# TODO: Update RPI
-# rpi-update
 
 # Generating ssh key pair
 if [ $FORCE -eq 1 ]; then
@@ -160,14 +170,14 @@ expect 1>$OPT_OUTPUT << EOF
 
   expect {
     timeout {
-      exit 2
+      exit 3
     }
     "Overwrite (y/n)?" {
       send $RESPONSE
       send "\r"
       expect {
         timeout {
-          exit 2
+          exit 4
         }
       }
     }
@@ -179,10 +189,10 @@ EXITCODE=$?
 
 if [ $EXITCODE -eq 2 ]; then
   log "👎  Key generation timed out. Try again or lower bits"
-  exit 3
+  exit 5
 elif [ $EXITCODE -ne 0 ]; then
   log "👎  Error generating key pair $KEYFILE"
-  exit 4
+  exit 6
 fi
 
 # Now lets install ansible
@@ -210,5 +220,8 @@ else
   log "👎  Someting went wrong."
 fi
 
-# TODO: optional reboot - check if needed
-# reboot
+# Optional reboot - check if needed
+if [ $REBOOT -eq 1 ]; then
+  log "🍅  REBOOT REQUIRED!"
+  exit 99
+fi
